from llm import Llm

# Video variants always use Gemini.
VIDEO_VARIANT_MODELS = (
    # Llm.GEMINI_3_FLASH_PREVIEW_MINIMAL,
    # Llm.GEMINI_3_1_PRO_PREVIEW_HIGH,
    Llm.GEMINI_2_5_FLASH,
    Llm.GEMINI_2_5_PRO,
)

# All API keys available.

# Image (Create)

ALL_KEYS_MODELS_DEFAULT = (
    # Llm.GEMINI_3_FLASH_PREVIEW_MINIMAL,
    Llm.GPT_5_2_CODEX_HIGH,
    # Llm.GEMINI_3_FLASH_PREVIEW_HIGH,
    # Llm.GEMINI_3_1_PRO_PREVIEW_HIGH,
    Llm.GEMINI_2_5_FLASH,
    Llm.GEMINI_2_5_PRO,
)

# Text (Create)

ALL_KEYS_MODELS_TEXT_CREATE = (
    # Llm.GEMINI_3_FLASH_PREVIEW_MINIMAL,
    Llm.GPT_5_2_CODEX_HIGH,
    Llm.CLAUDE_OPUS_4_6,
    # Llm.GEMINI_3_1_PRO_PREVIEW_LOW,
    Llm.GEMINI_2_5_FLASH,
    Llm.GEMINI_2_5_PRO,
)

# Image + Text (Update)

ALL_KEYS_MODELS_UPDATE = (
    # Llm.GEMINI_3_FLASH_PREVIEW_MINIMAL,
    Llm.GPT_5_4_2026_03_05_LOW,
    Llm.GEMINI_2_5_FLASH,
    Llm.GEMINI_2_5_PRO,
)

# Key subset fallbacks.
GEMINI_ANTHROPIC_MODELS = (
    # Llm.GEMINI_3_FLASH_PREVIEW_MINIMAL,
    # Llm.GEMINI_3_1_PRO_PREVIEW_LOW,
    Llm.CLAUDE_OPUS_4_6,
    # Llm.GEMINI_3_FLASH_PREVIEW_HIGH,
    # Llm.GEMINI_3_1_PRO_PREVIEW_HIGH,
    Llm.GEMINI_2_5_FLASH,
    Llm.GEMINI_2_5_PRO,
)
GEMINI_OPENAI_MODELS = (
    # Llm.GEMINI_3_FLASH_PREVIEW_MINIMAL,
    # Llm.GEMINI_3_1_PRO_PREVIEW_LOW,
    Llm.GPT_5_2_CODEX_HIGH,
    Llm.GPT_5_2_CODEX_MEDIUM,
    Llm.GEMINI_2_5_FLASH,
    Llm.GEMINI_2_5_PRO,
)
OPENAI_ANTHROPIC_MODELS = (
    Llm.CLAUDE_OPUS_4_6,
    Llm.GPT_5_2_CODEX_HIGH,
    Llm.GPT_5_2_CODEX_MEDIUM,
)
GEMINI_ONLY_MODELS = (
    # Llm.GEMINI_3_FLASH_PREVIEW_MINIMAL,
    # Llm.GEMINI_3_1_PRO_PREVIEW_LOW,
    # Llm.GEMINI_3_FLASH_PREVIEW_HIGH,
    # Llm.GEMINI_3_1_PRO_PREVIEW_HIGH,
    Llm.GEMINI_2_5_FLASH,
    Llm.GEMINI_2_5_PRO,
)
ANTHROPIC_ONLY_MODELS = (
    Llm.CLAUDE_OPUS_4_6,
    Llm.CLAUDE_SONNET_4_6,
)
OPENAI_ONLY_MODELS = (
    Llm.GPT_5_2_CODEX_HIGH,
    Llm.GPT_5_2_CODEX_MEDIUM,
)
